
application.version: 1.0.0
spring.output.ansi.enabled: ALWAYS
spring.web.resources.static-locations: file:resource-discovery/management/src/main/resources/static/freebees_webdesign_6

#security.ignored: /**
#security.basic.enable: false
#spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

#spring.security.user.name: user
#spring.security.user.password: user
#spring.security.user.roles: USER

server.servlet.session.timeout: 120m

spring.data.mongodb.uri: mongodb://root:example@localhost:27017/admin
spring.data.mongodb.database: resource_discovery

discovery:
  brokerUsername: "aaa"
  brokerPassword: "111"
  brokerURL: "tcp://localhost:61616?daemon=true&trace=false&useInactivityMonitor=false&connectionTimeout=0&keepAlive=true"
  allowedDeviceInfoKeys:
    - '*'
  users:
    - username: admin
      password: admin1
      roles: [ ADMIN ]
    - username: user
      password: user1
      roles: [ USER ]

#logging.level.eu.nebulous.resource.discovery.registration.RegistrationRequestProcessor: TRACE