
#security.ignored: /**
#security.basic.enable: false
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.web.resources.static-locations: file:resource-discovery/management/src/main/resources/static/freebees_webdesign_6