package eu.nebulous.resource.discovery.registration.model;

public enum RegistrationRequestStatus {
    NEW_REQUEST, PRE_AUTHORIZATION_REQUESTED, PRE_AUTHORIZATION_REJECT, PRE_AUTHORIZATION_ERROR,
    PENDING_DATA_COLLECTION, DATA_COLLECTION_REQUESTED, DATA_COLLECTION_ERROR,
    PENDING_AUTHORIZATION, AUTHORIZATION_REQUESTED, AUTHORIZATION_REJECT, AUTHORIZATION_ERROR,
    PENDING_ONBOARDING, ONBOARDING_REQUESTED, ONBOARDING_ERROR,
    SUCCESS
}
