name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-resource-discovery:
    name: Build and push resource-discovery
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: resource-discovery
      image-name: resource-discovery 
    secrets: inherit
